# Generated by Django 4.2.29 on 2026-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_ative",
            field=models.BooleanField(default=False, verbose_name="邮箱验证状态"),
        ),
    ]
