# Generated by Django 4.2.29 on 2026-04-10 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_email_ative"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_ative",
            new_name="email_active",
        ),
    ]
